name: Update Custom Fields on New Issue

on:
  issues:
    types:
      - opened

jobs:
  updateCustomFields:
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue information
        id: extract
        run: |
          echo "issue_number=$(jq --raw-output .issue.number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "repo_owner=$(jq --raw-output .repository.owner.login $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "repo_name=$(jq --raw-output .repository.name $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Trigger Google Apps Script
        run: |
          curl -X GET -L "https://script.google.com/macros/s/AKfycbyaiklWYkxBHtDUtpfAipM25QGd65tdChcl86B6k3-asgmWsaxqotTlFxeNopc2Hd6G/exec"

      - name: Set Custom Fields
        run: |
          # Retrieve the extracted information
          ISSUE_NUMBER=${{ steps.extract.outputs.issue_number }}
          REPO_OWNER=${{ steps.extract.outputs.repo_owner }}
          REPO_NAME=${{ steps.extract.outputs.repo_name }}

          # Make a request to the GitHub API to update the issue with the custom field values
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "fields": {
                "Severity": "${{ env.SEVERITY }}",
                "Environment": "${{ env.ENVIRONMENT }}",
                "Reported On": "${{ env.REPORTED_ON }}",
                "Epic-Features": "${{ env.EPIC_FEATURES }}",
                "Logged By": "${{ env.LOGGED_BY }}"
              }
            }' \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER"
